# Generated by Django 4.1.1 on 2024-07-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsaGrind', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(max_length=5000),
        ),
    ]
