
services:
  web:
    build: 
      context: .
    command: ["sh", "./start.sh"]
    volumes:
      - .:/app
    depends_on:
      - postgres_db
    ports:
      - "8000:8000"
    env_file:
      - .env

  postgres_db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${SQL_NAME}
      - POSTGRES_USER=${SQL_User}
      - POSTGRES_PASSWORD=${SQL_Password}
    ports:
      - "5433:5432"
    env_file:
      - .env

volumes:
  postgres_data:
